/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Trackers.java
 *
 * Created on 30-ago-2008, 21:23:42
 */
package rax2;

import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.xmlrpc.XmlRpcException;
import org.apache.xmlrpc.client.XmlRpcClient;

/**
 *
 * @author selu
 */
public class Trackers extends javax.swing.JFrame {

    private XmlRpcClient _client;
    private DefaultTableModel model;

    /** Creates new form Trackers
     * @param client */
    public Trackers(XmlRpcClient client) {
        initComponents();
        tablaRegexp.getColumnModel().getColumn(1).setMinWidth(60);
        tablaRegexp.getColumnModel().getColumn(1).setMaxWidth(60);
        _client = client;
        HashMap struct;

        try {
            Object[] params = new Object[]{};

            Object[] result = (Object[]) _client.execute("rssani.listaAuths", params);

            // Insertamos las regexps recibidas, haciendo casting
            for (int i = 0; i < result.length; ++i) {
                struct = (HashMap) result[i];
                model.addRow(new Object[]{struct.get("tracker"), struct.get("uid"), struct.get("pass"), struct.get("passkey")});
            }

            /*if (!result) {
            JOptionPane.showMessageDialog(this, "No se pudo cambiar", "Error", JOptionPane.WARNING_MESSAGE);
            } else {
            JOptionPane.showMessageDialog(this, "Se cambiaron los credenciales", "Exito", JOptionPane.INFORMATION_MESSAGE);
            }*/

        } catch (XmlRpcException ex) {
            JOptionPane.showMessageDialog(this, ex, "ola?", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegexp = new javax.swing.JTable();
        jButtonAnadir = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trackers"); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        model=new DefaultTableModel(){
            public Class getColumnClass(int columnIndex) {
                if (columnIndex==0){
                    return String.class;
                }else if (columnIndex==1){
                    return String.class;
                } else if (columnIndex==2){
                    return String.class;
                }
                return Object.class;
            }
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };

        model.addColumn("Tracker");
        model.addColumn("UID");
        model.addColumn("Password");
        model.addColumn("Passkey");
        tablaRegexp.setModel(model);
        tablaRegexp.setAlignmentX(1.0F);
        tablaRegexp.setAlignmentY(1.0F);
        tablaRegexp.setAutoscrolls(false);
        tablaRegexp.setName("tablaRegexp"); // NOI18N
        jScrollPane1.setViewportView(tablaRegexp);
        tablaRegexp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaRegexp.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tablaRegexp);

        jButtonAnadir.setText("Add"); // NOI18N
        jButtonAnadir.setName("jButtonAnadir"); // NOI18N
        jButtonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Remove"); // NOI18N
        jButtonBorrar.setName("jButtonBorrar"); // NOI18N
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAnadir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBorrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnadir)
                    .addComponent(jButtonBorrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        if (tablaRegexp.getSelectedRow() == -1) {
            return;
        }
        int si = JOptionPane.showConfirmDialog(this, "¿Esta seguro de eliminar " + tablaRegexp.getModel().getValueAt(tablaRegexp.convertRowIndexToModel(tablaRegexp.getSelectedRow()), 0) + "?", "Pregunta", javax.swing.JOptionPane.YES_NO_OPTION);
        if (si == 1) {
            return;
        }
        try {
            Object[] params = new Object[]{tablaRegexp.getModel().getValueAt(tablaRegexp.convertRowIndexToModel(tablaRegexp.getSelectedRow()), 0)};
            Boolean result = (Boolean) _client.execute("rssani.borrarAuth", params);

            model.removeRow(tablaRegexp.convertRowIndexToModel(tablaRegexp.getSelectedRow()));

        } catch (XmlRpcException ex) {
            JOptionPane.showMessageDialog(this, ex, "ola?", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirActionPerformed
        // Dialogo para el nuevo tracker
        String tracker = JOptionPane.showInputDialog("Introduce la url del tracker", "http://");
        if (tracker == null || tracker.equals("") || tracker.equals("http://")) {
            return;
        }

        // Dialogo para el uid
        String uid = JOptionPane.showInputDialog("Introduce el uid");
        if (uid == null) {
            return;
        }

        // Dialogo para el pass
        String pass = JOptionPane.showInputDialog("Introduce el hash del password");

        if (pass == null) {
            return;
        }

        // Dialogo para la passkey
        String passkey = JOptionPane.showInputDialog("Introduce la passkey");

        if (passkey == null) {
            return;
        }
        // Creamos la xmlrpc con los cuatro parametros
        try {
            Object[] params = new Object[]{tracker, uid, pass, passkey};

            Boolean result = (Boolean) _client.execute("rssani.anadirAuth", params);

            model.addRow(new Object[]{tracker, uid, pass});

        } catch (XmlRpcException ex) {
            JOptionPane.showMessageDialog(this, ex, "ola?", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAnadirActionPerformed
    /**
     * @param args the command line arguments
     */
    /*    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    new Trackers().setVisible(true);
    }
    });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadir;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRegexp;
    // End of variables declaration//GEN-END:variables
}
