/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Trackers.java
 *
 * Created on 30-ago-2008, 21:23:42
 */
package rax2;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import io.grpc.StatusRuntimeException;
import rax2.proto.RssaniServiceGrpc;
import rax2.proto.EmptyRequest;
import rax2.proto.AuthListResponse;
import rax2.proto.AnadirAuthRequest;
import rax2.proto.BorrarAuthRequest;
import rax2.proto.BoolResponse;

/**
 * Tracker authentication management dialog.
 * @author selu
 */
public class Trackers extends javax.swing.JFrame {

    /** gRPC stub for server communication. */
    private RssaniServiceGrpc.RssaniServiceBlockingStub _stub;
    /** Table model for tracker credentials. */
    private DefaultTableModel model;

    /**
     * Creates new form Trackers.
     * @param stub the gRPC blocking stub for server communication
     */
    public Trackers(RssaniServiceGrpc.RssaniServiceBlockingStub stub) {
        initComponents();
        tablaRegexp.getColumnModel().getColumn(1).setMinWidth(60);
        tablaRegexp.getColumnModel().getColumn(1).setMaxWidth(60);
        _stub = stub;
        try {
            EmptyRequest empty = EmptyRequest.getDefaultInstance();
            AuthListResponse result = _stub.listaAuths(empty);

            for (int i = 0; i < result.getEntriesCount(); ++i) {
                var entry = result.getEntries(i);
                TrackerAuth auth = new TrackerAuth(
                        entry.getTracker(),
                        entry.getUid(),
                        entry.getPass(),
                        entry.getPasskey());
                model.addRow(new Object[]{auth.getTracker(), auth.getUid(), auth.getPass(), auth.getPasskey()});
            }

        } catch (StatusRuntimeException ex) {
            GrpcErrorHandler.showErrorMessage(this, ex, "Error");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegexp = new javax.swing.JTable();
        jButtonAnadir = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trackers"); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        model=new DefaultTableModel(){
            public Class getColumnClass(int columnIndex) {
                if (columnIndex==0){
                    return String.class;
                }else if (columnIndex==1){
                    return String.class;
                } else if (columnIndex==2){
                    return String.class;
                }
                return Object.class;
            }
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };

        model.addColumn("Tracker");
        model.addColumn("UID");
        model.addColumn("Password");
        model.addColumn("Passkey");
        tablaRegexp.setModel(model);
        tablaRegexp.setAlignmentX(1.0F);
        tablaRegexp.setAlignmentY(1.0F);
        tablaRegexp.setAutoscrolls(false);
        tablaRegexp.setName("tablaRegexp"); // NOI18N
        jScrollPane1.setViewportView(tablaRegexp);
        tablaRegexp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaRegexp.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tablaRegexp);

        jButtonAnadir.setText("Add"); // NOI18N
        jButtonAnadir.setName("jButtonAnadir"); // NOI18N
        jButtonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Remove"); // NOI18N
        jButtonBorrar.setName("jButtonBorrar"); // NOI18N
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAnadir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBorrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnadir)
                    .addComponent(jButtonBorrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        if (tablaRegexp.getSelectedRow() == -1) {
            return;
        }
        int si = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete " + tablaRegexp.getModel().getValueAt(tablaRegexp.convertRowIndexToModel(tablaRegexp.getSelectedRow()), 0) + "?", "Confirm", javax.swing.JOptionPane.YES_NO_OPTION);
        if (si == 1) {
            return;
        }
        try {
            String tracker = tablaRegexp.getModel().getValueAt(tablaRegexp.convertRowIndexToModel(tablaRegexp.getSelectedRow()), 0).toString();
            BorrarAuthRequest request = BorrarAuthRequest.newBuilder()
                    .setTracker(tracker)
                    .build();
            _stub.borrarAuth(request);

            model.removeRow(tablaRegexp.convertRowIndexToModel(tablaRegexp.getSelectedRow()));

        } catch (StatusRuntimeException ex) {
            GrpcErrorHandler.showErrorMessage(this, ex, "Error");
        }
}//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirActionPerformed
        // Dialogo para el nuevo tracker
        String tracker = JOptionPane.showInputDialog("Enter the tracker URL", "http://");
        if (tracker == null || tracker.equals("") || tracker.equals("http://")) {
            return;
        }

        // Dialogo para el uid
        String uid = JOptionPane.showInputDialog("Enter the UID");
        if (uid == null) {
            return;
        }

        // Dialogo para el pass
        String pass = JOptionPane.showInputDialog("Enter the password hash");

        if (pass == null) {
            return;
        }

        // Dialogo para la passkey
        String passkey = JOptionPane.showInputDialog("Enter the passkey");

        if (passkey == null) {
            return;
        }
        // Creamos la llamada gRPC con los cuatro parametros
        try {
            AnadirAuthRequest request = AnadirAuthRequest.newBuilder()
                    .setTracker(tracker)
                    .setUid(uid)
                    .setPassword(pass)
                    .setPasskey(passkey)
                    .build();

            _stub.anadirAuth(request);

            model.addRow(new Object[]{tracker, uid, pass, passkey});

        } catch (StatusRuntimeException ex) {
            GrpcErrorHandler.showErrorMessage(this, ex, "Error");
        }
    }//GEN-LAST:event_jButtonAnadirActionPerformed
    /*
     * @param args the command line arguments
     */
    /*    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    new Trackers().setVisible(true);
    }
    });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    /** Add tracker button. */
    private javax.swing.JButton jButtonAnadir;
    /** Remove tracker button. */
    private javax.swing.JButton jButtonBorrar;
    /** Scroll pane for the trackers table. */
    private javax.swing.JScrollPane jScrollPane1;
    /** Table displaying tracker credentials. */
    private javax.swing.JTable tablaRegexp;
    // End of variables declaration//GEN-END:variables
}
